print("Por favor, insira as seguintes informações:")
first_name = input("Digite seu primeiro nome: ")
last_name = input("Digite seu sobrenome: ")
email = input("Digite seu email: ")
phone_number = input("Digite seu número de telefone (com DDD): ")
job_title = input("Digite seu cargo: ")
identification_number = input("Digite seu número de identificação: ")
hair_color = input("Digite a cor do seu cabelo: ")
eye_color = input("Digite a cor dos seus olhos: ")
entry_month = input("Digite o mês de entrada: ")
training_conclusion = input("Você concluiu o treinamento? (sim/não): ")

print("O crachá de identificação é:")
print("-" * 35)
print(last_name.upper() + ", " + first_name.title())
print(job_title.title())
print(f"Identificação: {identification_number}")
print()
print(email.lower())
print(f"({phone_number[:2]}) {phone_number[2:7]}-{phone_number[7:]}")
print()
print(f"Cabelo: {hair_color.title()}     Olhos: {eye_color.title()}")
print(f"Mês:{entry_month.title()}     Treinamento: {training_conclusion.title()}")
print("-" * 35)